### ISSUE TITLE
Empty LeaderBoard Page

### ISSUE THREAD

**Issue by freedompraise** [KaranRansing2002/pokemon-battle-simulator#1]
The leaderboard page still hasn't been worked on after quite a while. 

Is there any progress?
Is it something I can look into and work on? @KaranRansing2002

**Comment by KaranRansing2002** [comment]
@freedompraise 
Yeah, there was some battle calculation issue I was going to fix/upgrade  therefore couldn't able to create a rating feature 
I will be fixing it in this week 
feel free to contribute, You could create a skeleton/design of the leaderboard page or could suggest some ideas

**Comment by freedompraise** [comment]
Alright.
I'd come up with something

**Comment by Alanmp1857** [comment]
I have also some ideas for the leaderboard. Sharing the idea

![image](https://github.com/KaranRansing2002/pokemon-battle-simulator/assets/95167331/cf0f31bc-9970-4097-9bb2-89b3d7314653)
